[[redirects]]
  from = "/.well-known/*"
  to = "/.well-known/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/.well-known/*"
  [headers.values]
    Content-Type = "text/plain"
    X-Content-Type-Options = "nosniff" 